[package]
name = 'patch_nominal_reward_migration_error'
version = '1.0.0'
authors = []
license = ''

[addresses]

[dev-addresses]
[dependencies.LibraFramework]
local = '/home/zoz/libra-framework/framework/libra-framework'

[dev-dependencies]
