[package]
name = 'upgrade_scripts'
version = '1.0.0'
authors = []
license = ''

[addresses]

[dev-addresses]
[dependencies.LibraFramework]
local = '/home/david/projects/libra/upstream/libra-framework/framework/libra-framework'

[dev-dependencies]
