[package]
name = 'enter_governance_mode'
version = '1.0.0'
authors = []
license = ''

[addresses]

[dev-addresses]
[dependencies.LibraFramework]
local = '../libra-framework/framework/libra-framework'

[dev-dependencies]
